# API Configuration (Optional)
[api]
openrouter_api_key = "your-api-key-here"
openrouter_model = "qwen/qwq-32b:free"
openrouter_base_url = "https://openrouter.ai/api/v1"

# App Settings
[app]
debug = false
version = "2.0.0"
