# API Configuration
[api]
openrouter_api_key = "your-openrouter-api-key-here"
openrouter_model = "qwen/qwq-32b:free"
openrouter_base_url = "https://openrouter.ai/api/v1"

# App Configuration
[app]
title = "Green Smart EcoTourism AI"
version = "2.0.0"
debug = false

# Cache Settings
[cache]
ttl = 300
max_entries = 100
